data = [
    {"name": "Cristiano Ronaldo", "description": "a Footballer", "country": "Portugal", "follower_count": 630},
    {"name": "Lionel Messi", "description": "a Footballer", "country": "Argentina", "follower_count": 500},
    {"name": "Neymar Jr", "description": "a Footballer", "country": "Brazil", "follower_count": 210},
    {"name": "Virat Kohli", "description": "a Cricketer", "country": "India", "follower_count": 260},
    {"name": "Babar Azam", "description": "a Cricketer", "country": "Pakistan", "follower_count": 20},
    {"name": "MS Dhoni", "description": "a Cricketer", "country": "India", "follower_count": 50},
    {"name": "Shahid Afridi", "description": "a Cricketer", "country": "Pakistan", "follower_count": 10},
    {"name": "Dwayne Johnson", "description": "an Actor", "country": "United States", "follower_count": 395},
    {"name": "Zendaya", "description": "an Actress and musician", "country": "United States", "follower_count": 185},
    {"name": "Shah Rukh Khan", "description": "an Actor", "country": "India", "follower_count": 45},
    {"name": "Priyanka Chopra", "description": "an Actress", "country": "India", "follower_count": 90},
    {"name": "Selena Gomez", "description": "a Musician and actress", "country": "United States", "follower_count": 425},
    {"name": "Ariana Grande", "description": "a Musician", "country": "United States", "follower_count": 380},
    {"name": "Justin Bieber", "description": "a Musician", "country": "Canada", "follower_count": 290},
    {"name": "Elon Musk", "description": "a Businessman", "country": "United States", "follower_count": 15},
    {"name": "Kim Kardashian", "description": "a Media personality", "country": "United States", "follower_count": 360},
    {"name": "Kylie Jenner", "description": "a Media personality", "country": "United States", "follower_count": 400},
    {"name": "Rohit Sharma", "description": "a Cricketer", "country": "India", "follower_count": 30},
    {"name": "Kylian Mbappe", "description": "a Footballer", "country": "France", "follower_count": 120},
    {"name": "Imran Khan", "description": "a Cricketer and Politician", "country": "Pakistan", "follower_count": 18},
]
