SHEETY_PRICES_ENDPOINT = "YOUR_SHEETY_PRICES_ENDPOINT_HERE"
SHEETY_USERS_ENDPOINT = "YOUR_SHEETY_USERS_ENDPOINT_HERE"
SHEETY_USERNAME = "YOUR_SHEETY_USERNAME_HERE"
SHEETY_PASSWORD = "YOUR_SHEETY_PASSWORD_HERE"

RAPIDAPI_KEY = "YOUR_RAPIDAPI_KEY_HERE"

MY_EMAIL = "YOUR_EMAIL@gmail.com"
MY_PASSWORD = "YOUR_16_CHAR_APP_PASSWORD"